// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAADvqAEnCY0rhPDGyh2c2u9PoGszuKDHk',
    appId: '1:426176569293:web:1481acb03ee6f50e962e84',
    messagingSenderId: '426176569293',
    projectId: 'thisisme-7e596',
    authDomain: 'thisisme-7e596.firebaseapp.com',
    storageBucket: 'thisisme-7e596.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8dvEw2OEge4MxtUFIiG5GHYOHrT1CG50',
    appId: '1:426176569293:android:a98b6d0409146a9d962e84',
    messagingSenderId: '426176569293',
    projectId: 'thisisme-7e596',
    storageBucket: 'thisisme-7e596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8O08t3lPmaODoBghYEB5-Ztpad_FqVxA',
    appId: '1:426176569293:ios:402ce3eeb48ba25d962e84',
    messagingSenderId: '426176569293',
    projectId: 'thisisme-7e596',
    storageBucket: 'thisisme-7e596.appspot.com',
    iosBundleId: 'com.example.thisismeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8O08t3lPmaODoBghYEB5-Ztpad_FqVxA',
    appId: '1:426176569293:ios:2329abf988a5993d962e84',
    messagingSenderId: '426176569293',
    projectId: 'thisisme-7e596',
    storageBucket: 'thisisme-7e596.appspot.com',
    iosBundleId: 'com.example.thisismeapp.RunnerTests',
  );
}
